# Generated by Django 4.2.7 on 2024-01-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transfer_another_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brank_Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brank_craft', models.BooleanField(default=False)),
            ],
        ),
    ]
